### PR TITLE
Make compatible with Rails 5

### PR DESCRIPTION
**Pull request by lazyatom**
In Rails 5, `ActiveRecord::RelationAssociation` no longer delegates to `Array`, so we cannot use methods like `:<<` to temporarily add preference objects to the internal `saved_preferences` collection.

The simplest resolution is to use `#save` to immediately persist the new preference, and then call `#reload` once all of the preferences have been persisted. This allows the expected behaviour and tests to continue to pass, at the potential expense of a few more database queries when setting preferences.

### CODE REVIEW

**Comment by andydust** [comment]
My main concern is that we now end up temporarily persisting a preference with a potentially different value to the one that was the API was trying to set, which can result in unexpected side-effects. For example, in MA `Mailchimp::SyncTriggers` adds some AR callbacks onto the preference model. That particular one is using after_commit so it should be okay I think since we're using a transaction here in the preferences gem? But other clients might use other callbacks.

If we can't add the preference to the array and defer persistence to the very end of this code path (`Preference#update_value!`), could we explore initializing the preference with the desired value by passing it as a parameter to `find_or_init_preference` along with name?

**Comment by lazyatom** [comment]
I *think* I can see the case you mean; if one thread has completed the call to `find_or_init_preference` but not the `update_value!` method, then another thread (or process) might read the wrong value. Is that right?

**Comment by andydust** [comment]
@lazyatom and I discussed this further on Slack. The latest commit resolves the potential unintended callback side effect issue and we discussed potentially defining official hooks for when gem users do want callbacks without worrying about the underlying implementation details. One for a follow up PR. 

This LGTM.

**Comment by lazyatom** [comment]
I guess the only remaining thing to do is pick a new version number; since this change "breaks" support for Rails 3, that might be best signalled via a major version change - "1.0.0"?

**Comment by andydust** [comment]
sounds gd

**Pull request merged**
